// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzfkU1Go21O8YTwDxB1E7US7JSRI7iEw',
    appId: '1:375111950781:web:583758cb6527aae4c332d4',
    messagingSenderId: '375111950781',
    projectId: 'event-demo-90383',
    authDomain: 'event-demo-90383.firebaseapp.com',
    storageBucket: 'event-demo-90383.firebasestorage.app',
    measurementId: 'G-Q0GF5Q5B6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGV-5lwLMSYEv71vRktDinPVpw5an4Uw',
    appId: '1:375111950781:android:e4d03c92e0c0849ac332d4',
    messagingSenderId: '375111950781',
    projectId: 'event-demo-90383',
    storageBucket: 'event-demo-90383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHXDvFwbJmyJi6T8k8P0nRL4wSb4hnnM',
    appId: '1:375111950781:ios:1e5e3cfc0fa5f010c332d4',
    messagingSenderId: '375111950781',
    projectId: 'event-demo-90383',
    storageBucket: 'event-demo-90383.firebasestorage.app',
    iosBundleId: 'com.example.eventNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcHXDvFwbJmyJi6T8k8P0nRL4wSb4hnnM',
    appId: '1:375111950781:ios:1e5e3cfc0fa5f010c332d4',
    messagingSenderId: '375111950781',
    projectId: 'event-demo-90383',
    storageBucket: 'event-demo-90383.firebasestorage.app',
    iosBundleId: 'com.example.eventNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhzfkU1Go21O8YTwDxB1E7US7JSRI7iEw',
    appId: '1:375111950781:web:aa7b5101cd818cebc332d4',
    messagingSenderId: '375111950781',
    projectId: 'event-demo-90383',
    authDomain: 'event-demo-90383.firebaseapp.com',
    storageBucket: 'event-demo-90383.firebasestorage.app',
    measurementId: 'G-NKENT017TV',
  );
}
